# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _gribapi_swig
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


cdata = _gribapi_swig.cdata
memmove = _gribapi_swig.memmove
GRIB_SUCCESS = _gribapi_swig.GRIB_SUCCESS
GRIB_END_OF_FILE = _gribapi_swig.GRIB_END_OF_FILE
GRIB_INTERNAL_ERROR = _gribapi_swig.GRIB_INTERNAL_ERROR
GRIB_BUFFER_TOO_SMALL = _gribapi_swig.GRIB_BUFFER_TOO_SMALL
GRIB_NOT_IMPLEMENTED = _gribapi_swig.GRIB_NOT_IMPLEMENTED
GRIB_7777_NOT_FOUND = _gribapi_swig.GRIB_7777_NOT_FOUND
GRIB_ARRAY_TOO_SMALL = _gribapi_swig.GRIB_ARRAY_TOO_SMALL
GRIB_FILE_NOT_FOUND = _gribapi_swig.GRIB_FILE_NOT_FOUND
GRIB_CODE_NOT_FOUND_IN_TABLE = _gribapi_swig.GRIB_CODE_NOT_FOUND_IN_TABLE
GRIB_WRONG_ARRAY_SIZE = _gribapi_swig.GRIB_WRONG_ARRAY_SIZE
GRIB_NOT_FOUND = _gribapi_swig.GRIB_NOT_FOUND
GRIB_IO_PROBLEM = _gribapi_swig.GRIB_IO_PROBLEM
GRIB_INVALID_MESSAGE = _gribapi_swig.GRIB_INVALID_MESSAGE
GRIB_DECODING_ERROR = _gribapi_swig.GRIB_DECODING_ERROR
GRIB_ENCODING_ERROR = _gribapi_swig.GRIB_ENCODING_ERROR
GRIB_NO_MORE_IN_SET = _gribapi_swig.GRIB_NO_MORE_IN_SET
GRIB_GEOCALCULUS_PROBLEM = _gribapi_swig.GRIB_GEOCALCULUS_PROBLEM
GRIB_OUT_OF_MEMORY = _gribapi_swig.GRIB_OUT_OF_MEMORY
GRIB_READ_ONLY = _gribapi_swig.GRIB_READ_ONLY
GRIB_INVALID_ARGUMENT = _gribapi_swig.GRIB_INVALID_ARGUMENT
GRIB_NULL_HANDLE = _gribapi_swig.GRIB_NULL_HANDLE
GRIB_INVALID_SECTION_NUMBER = _gribapi_swig.GRIB_INVALID_SECTION_NUMBER
GRIB_VALUE_CANNOT_BE_MISSING = _gribapi_swig.GRIB_VALUE_CANNOT_BE_MISSING
GRIB_WRONG_LENGTH = _gribapi_swig.GRIB_WRONG_LENGTH
GRIB_INVALID_TYPE = _gribapi_swig.GRIB_INVALID_TYPE
GRIB_WRONG_STEP = _gribapi_swig.GRIB_WRONG_STEP
GRIB_WRONG_STEP_UNIT = _gribapi_swig.GRIB_WRONG_STEP_UNIT
GRIB_INVALID_FILE = _gribapi_swig.GRIB_INVALID_FILE
GRIB_INVALID_GRIB = _gribapi_swig.GRIB_INVALID_GRIB
GRIB_INVALID_INDEX = _gribapi_swig.GRIB_INVALID_INDEX
GRIB_INVALID_ITERATOR = _gribapi_swig.GRIB_INVALID_ITERATOR
GRIB_INVALID_KEYS_ITERATOR = _gribapi_swig.GRIB_INVALID_KEYS_ITERATOR
GRIB_INVALID_NEAREST = _gribapi_swig.GRIB_INVALID_NEAREST
GRIB_INVALID_ORDERBY = _gribapi_swig.GRIB_INVALID_ORDERBY
GRIB_MISSING_KEY = _gribapi_swig.GRIB_MISSING_KEY
GRIB_OUT_OF_AREA = _gribapi_swig.GRIB_OUT_OF_AREA
GRIB_CONCEPT_NO_MATCH = _gribapi_swig.GRIB_CONCEPT_NO_MATCH
GRIB_NO_DEFINITIONS = _gribapi_swig.GRIB_NO_DEFINITIONS
GRIB_WRONG_TYPE = _gribapi_swig.GRIB_WRONG_TYPE
GRIB_END = _gribapi_swig.GRIB_END
GRIB_NO_VALUES = _gribapi_swig.GRIB_NO_VALUES
GRIB_WRONG_GRID = _gribapi_swig.GRIB_WRONG_GRID
GRIB_END_OF_INDEX = _gribapi_swig.GRIB_END_OF_INDEX
GRIB_NULL_INDEX = _gribapi_swig.GRIB_NULL_INDEX
GRIB_PREMATURE_END_OF_FILE = _gribapi_swig.GRIB_PREMATURE_END_OF_FILE
GRIB_INTERNAL_ARRAY_TOO_SMALL = _gribapi_swig.GRIB_INTERNAL_ARRAY_TOO_SMALL
GRIB_MESSAGE_TOO_LARGE = _gribapi_swig.GRIB_MESSAGE_TOO_LARGE
GRIB_CONSTANT_FIELD = _gribapi_swig.GRIB_CONSTANT_FIELD
GRIB_SWITCH_NO_MATCH = _gribapi_swig.GRIB_SWITCH_NO_MATCH
GRIB_UNDERFLOW = _gribapi_swig.GRIB_UNDERFLOW
GRIB_MESSAGE_MALFORMED = _gribapi_swig.GRIB_MESSAGE_MALFORMED
GRIB_CORRUPTED_INDEX = _gribapi_swig.GRIB_CORRUPTED_INDEX
GRIB_INVALID_BPV = _gribapi_swig.GRIB_INVALID_BPV
GRIB_DIFFERENT_EDITION = _gribapi_swig.GRIB_DIFFERENT_EDITION
GRIB_VALUE_DIFFERENT = _gribapi_swig.GRIB_VALUE_DIFFERENT
class intp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, intp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, intp, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _gribapi_swig.new_intp(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _gribapi_swig.delete_intp
    __del__ = lambda self : None;
    def assign(*args): return _gribapi_swig.intp_assign(*args)
    def value(*args): return _gribapi_swig.intp_value(*args)
    def cast(*args): return _gribapi_swig.intp_cast(*args)
    __swig_getmethods__["frompointer"] = lambda x: _gribapi_swig.intp_frompointer
    if _newclass:frompointer = staticmethod(_gribapi_swig.intp_frompointer)
intp_swigregister = _gribapi_swig.intp_swigregister
intp_swigregister(intp)
intp_frompointer = _gribapi_swig.intp_frompointer

class longp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, longp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, longp, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _gribapi_swig.new_longp(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _gribapi_swig.delete_longp
    __del__ = lambda self : None;
    def assign(*args): return _gribapi_swig.longp_assign(*args)
    def value(*args): return _gribapi_swig.longp_value(*args)
    def cast(*args): return _gribapi_swig.longp_cast(*args)
    __swig_getmethods__["frompointer"] = lambda x: _gribapi_swig.longp_frompointer
    if _newclass:frompointer = staticmethod(_gribapi_swig.longp_frompointer)
longp_swigregister = _gribapi_swig.longp_swigregister
longp_swigregister(longp)
longp_frompointer = _gribapi_swig.longp_frompointer

class doublep(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, doublep, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, doublep, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _gribapi_swig.new_doublep(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _gribapi_swig.delete_doublep
    __del__ = lambda self : None;
    def assign(*args): return _gribapi_swig.doublep_assign(*args)
    def value(*args): return _gribapi_swig.doublep_value(*args)
    def cast(*args): return _gribapi_swig.doublep_cast(*args)
    __swig_getmethods__["frompointer"] = lambda x: _gribapi_swig.doublep_frompointer
    if _newclass:frompointer = staticmethod(_gribapi_swig.doublep_frompointer)
doublep_swigregister = _gribapi_swig.doublep_swigregister
doublep_swigregister(doublep)
doublep_frompointer = _gribapi_swig.doublep_frompointer

new_doubleArray = _gribapi_swig.new_doubleArray
delete_doubleArray = _gribapi_swig.delete_doubleArray
doubleArray_getitem = _gribapi_swig.doubleArray_getitem
doubleArray_setitem = _gribapi_swig.doubleArray_setitem
new_longArray = _gribapi_swig.new_longArray
delete_longArray = _gribapi_swig.delete_longArray
longArray_getitem = _gribapi_swig.longArray_getitem
longArray_setitem = _gribapi_swig.longArray_setitem
new_intArray = _gribapi_swig.new_intArray
delete_intArray = _gribapi_swig.delete_intArray
intArray_getitem = _gribapi_swig.intArray_getitem
intArray_setitem = _gribapi_swig.intArray_setitem
grib_c_new_from_file = _gribapi_swig.grib_c_new_from_file
grib_c_iterator_new = _gribapi_swig.grib_c_iterator_new
grib_c_keys_iterator_new = _gribapi_swig.grib_c_keys_iterator_new
grib_c_new_from_samples = _gribapi_swig.grib_c_new_from_samples
grib_c_index_new_from_file = _gribapi_swig.grib_c_index_new_from_file
grib_c_new_from_index = _gribapi_swig.grib_c_new_from_index
grib_c_index_write = _gribapi_swig.grib_c_index_write
grib_c_index_read = _gribapi_swig.grib_c_index_read
grib_c_count_in_file = _gribapi_swig.grib_c_count_in_file
grib_c_release = _gribapi_swig.grib_c_release
grib_c_write = _gribapi_swig.grib_c_write
grib_c_get_size_long = _gribapi_swig.grib_c_get_size_long
grib_c_clone = _gribapi_swig.grib_c_clone
grib_c_copy_namespace = _gribapi_swig.grib_c_copy_namespace
grib_c_get_message_size = _gribapi_swig.grib_c_get_message_size
grib_c_get_native_type = _gribapi_swig.grib_c_get_native_type
grib_c_multi_new = _gribapi_swig.grib_c_multi_new
grib_c_multi_support_on = _gribapi_swig.grib_c_multi_support_on
grib_c_multi_write = _gribapi_swig.grib_c_multi_write
grib_c_multi_support_off = _gribapi_swig.grib_c_multi_support_off
grib_c_multi_release = _gribapi_swig.grib_c_multi_release
grib_c_multi_append = _gribapi_swig.grib_c_multi_append
grib_c_gribex_mode_on = _gribapi_swig.grib_c_gribex_mode_on
grib_c_gribex_mode_off = _gribapi_swig.grib_c_gribex_mode_off
grib_c_keys_iterator_next = _gribapi_swig.grib_c_keys_iterator_next
grib_c_keys_iterator_delete = _gribapi_swig.grib_c_keys_iterator_delete
grib_c_skip_computed = _gribapi_swig.grib_c_skip_computed
grib_c_skip_coded = _gribapi_swig.grib_c_skip_coded
grib_c_skip_edition_specific = _gribapi_swig.grib_c_skip_edition_specific
grib_c_skip_duplicates = _gribapi_swig.grib_c_skip_duplicates
grib_c_skip_read_only = _gribapi_swig.grib_c_skip_read_only
grib_c_skip_function = _gribapi_swig.grib_c_skip_function
grib_c_keys_iterator_rewind = _gribapi_swig.grib_c_keys_iterator_rewind
grib_c_keys_iterator_get_name = _gribapi_swig.grib_c_keys_iterator_get_name
grib_c_index_get_size_long = _gribapi_swig.grib_c_index_get_size_long
grib_c_index_get_long = _gribapi_swig.grib_c_index_get_long
grib_c_index_get_real8 = _gribapi_swig.grib_c_index_get_real8
grib_c_index_get_string = _gribapi_swig.grib_c_index_get_string
grib_c_index_select_long = _gribapi_swig.grib_c_index_select_long
grib_c_index_select_real8 = _gribapi_swig.grib_c_index_select_real8
grib_c_index_select_string = _gribapi_swig.grib_c_index_select_string
grib_c_index_release = _gribapi_swig.grib_c_index_release
grib_c_iterator_delete = _gribapi_swig.grib_c_iterator_delete
grib_c_iterator_next = _gribapi_swig.grib_c_iterator_next
grib_c_get_string = _gribapi_swig.grib_c_get_string
grib_c_set_string = _gribapi_swig.grib_c_set_string
grib_c_get_long = _gribapi_swig.grib_c_get_long
grib_c_set_long = _gribapi_swig.grib_c_set_long
grib_c_get_double = _gribapi_swig.grib_c_get_double
grib_c_set_double = _gribapi_swig.grib_c_set_double
grib_c_set_real8_array = _gribapi_swig.grib_c_set_real8_array
grib_c_get_real8_array = _gribapi_swig.grib_c_get_real8_array
grib_c_get_long_array = _gribapi_swig.grib_c_get_long_array
grib_c_set_long_array = _gribapi_swig.grib_c_set_long_array
grib_c_get_real8_element = _gribapi_swig.grib_c_get_real8_element
grib_c_get_real8_elements = _gribapi_swig.grib_c_get_real8_elements
grib_c_set_missing = _gribapi_swig.grib_c_set_missing
grib_c_is_missing = _gribapi_swig.grib_c_is_missing
with_numpy = _gribapi_swig.with_numpy
grib_set_double_ndarray = _gribapi_swig.grib_set_double_ndarray
grib_set_long_ndarray = _gribapi_swig.grib_set_long_ndarray
grib_get_double_ndarray = _gribapi_swig.grib_get_double_ndarray
grib_get_long_ndarray = _gribapi_swig.grib_get_long_ndarray
grib_get_double_ndelements = _gribapi_swig.grib_get_double_ndelements
grib_c_find_nearest_single = _gribapi_swig.grib_c_find_nearest_single
grib_c_find_nearest_four_single = _gribapi_swig.grib_c_find_nearest_four_single
grib_c_get_error_string = _gribapi_swig.grib_c_get_error_string
no_fail_on_wrong_length = _gribapi_swig.no_fail_on_wrong_length
grib_c_get_api_version = _gribapi_swig.grib_c_get_api_version
grib_c_gts_header_on = _gribapi_swig.grib_c_gts_header_on
grib_c_gts_header_off = _gribapi_swig.grib_c_gts_header_off


