# config file for creating experiments
# toml table layout:

[dates]
year = 2018
n_periods = 5
frequency = "annual"

[setup]
ini_file = "/group/chem/acrg/PARIS_inversions/hfc134a/annual_synthetic_no_bc/config.ini"
job_root = "/group/chem/acrg/PARIS_inversions/hfc134a"
python_venv = "/user/work/bm13805/.jax_venv"
job_name = "synth_test"
out_prefix = "annual_synthetic_no_bc"

[slurm]
n_cpu = 4
time = "02:30:00"
mem = "40gb"

[kwargs]
emissions_name = [["edgar-annual-total"], ["flat-annual-total"]]
use_bc = [True, False]

nuts_sampler = "numpyro"
nbasis = 500
basis_algorithm = "weighted"


[names]
emissions_name = ["EDGAR", "FLAT"]
use_bc = ["rhime_baseline_optimized", "intem_baseline_fixed"]
