; GOSAT process parameter file

[MEASUREMENTS]
; Details of GOSAT Measurements

input_directory = "/group/chem/acrg/obs_raw/TCCON/" ; Location of input GOSAT files
species = "ch4"                                                   ; Species GOSAT files are related to

[MEASUREMENTS.SELECTION]
; Criteria to select data to process within GOSAT dataset

site = "HARWELL"          ; Name of site (will be included in any output name) (str)
start = '2021-05-01'           ; Start of date range of selection (optional) (str in format YYYY-MM-DD)
end = '2021-12-01'             ; End of date range of selection (optional) (str in format YYYY-MM-DD)
coord_bin = [0.01,0.01]      ; Fictive binning to be used for creating NAME footprints.

[MEASUREMENTS.FILTER]
; Filters to apply to the data based on flags

quality_filt = False      ; Remove data points where quality filter flag indicates possible bad data

[NAME.OUTPUT]
; Parameters for NAME input csv file

write_name = True           ; Whether to write NAME file
name_directory = "/user/work/bq24992/workingDir/TCCON_NAME/NAME_files/" ; Base directory to write NAME output. Delete input to use default.

[NC.OUTPUT]
; Parameters for netCDF output file

write_nc = False                         ; Whether to write a simulatenous netCDF file
output_directory = "/user/work/bq24992/workingDir/TCCON_NAME/NC_files/" ; Base directory to write netCDF output. Delete input to use default.

[OUTPUT]
; Parameters to apply to all output files

file_per_day = True     ; Whether to include all points for one day in one file or in multiple files
overwrite = True        ; Whether to overwrite a NAME or netCDF file if it is already present.