name: acrg-hr
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - iris
  - ipython
  - scipy
  - future
  - xarray
  - yaml
  - scipy
  - matplotlib
  - cartopy
  - numba
  - pandas
  - h5py
  - python-dateutil
  - netCDF4
  - xESMF
  - geopandas

