# This is a variable version environment.yml file. Will download whichever version of the packages are available when environment is created.
name: acrg_var
channels:
  - conda-forge
dependencies:
  - python
  - pymc3
  - matplotlib-base
  - netcdf4
  - numpy
  - regionmask
  - xarray
  - iso3166
  - pandas
  - numexpr
  - tqdm
  - xesmf
  - geopandas
  - yaml
  - iris
  - cartopy
  - h5py
  - numba
  - scipy
  - pytest
  - pytest-mock
  - pyfakefs
  - cachetools
  - pip:
    - openghg_defs @ git+https://github.com/openghg/supplementary_data
