name: acrg_dry
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pymc
  - matplotlib-base=3.7
  - netcdf4=1.6
  - numpy>=1.26
  - regionmask=0.9
  - xarray=2024.10
  - iso3166=2.1
  - pandas=2.0
  - numexpr=2.8
  - tqdm=4.64
  - xesmf=0.7
  - geopandas=0.14
  - yaml=0.2
  - iris=3.4
  - cartopy=0.22
  - h5py=3.8
  - numba=0.57
  - scipy=1.10
  - pytest=9.0.1
  - pyfakefs=5.1
  - cachetools=5.3
  - pip:
    - openghg_defs @ git+https://github.com/openghg/openghg_defs
