name: acrg
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pymc3=3.11
  - matplotlib-base=3.5
  - netcdf4=1.5
  - numpy=1.21
  - regionmask=0.9
  - xarray=2022.3
  - iso3166=2.0
  - pandas=1.4
  - numexpr=2.8
  - tqdm=4.64
  - xesmf=0.6
  - geopandas=0.10
  - yaml=0.2
  - iris=3.2
  - cartopy=0.20
  - h5py=3.6
  - numba=0.55
  - scipy=1.8
  - pytest=7.1
  - pyfakefs=4.5
  - pip:
    - openghg_defs @ git+https://github.com/openghg/supplementary_data
