name: acrg
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pymc3=3.9
  - matplotlib-base=3.7
  - netcdf4=1.6
  - numpy=1.22
  - regionmask=0.9
  - xarray=2023.2
  - iso3166=2.1
  - pandas=1.5
  - numexpr=2.8
  - tqdm=4.64
  - xesmf=0.7
  - geopandas=0.12
  - yaml=0.2
  - iris=3.4
  - cartopy=0.21
  - h5py=3.8
  - numba=0.56
  - scipy=1.10
  - pytest=7.2
  - pyfakefs=5.1
  - cachetools=5.3
  - pip:
    - openghg_defs @ git+https://github.com/openghg/supplementary_data
