# This is a variable version acrg_environment.yml file. Will download whichever version of the packages are available when environment is created.
name: acrg_var
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - scipy
  - pandas
  - h5py
  - netCDF4
  - xarray
  - matplotlib-base
  - cartopy
  - geopandas
  - iris
  - pymc3
  - yaml
  - numba
  - iso3166