name: acrg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.18.1
  - scipy=1.4.1
  - pandas=1.0.3
  - h5py=2.10.0
  - netcdf4=1.5.3
  - xarray=0.15.1
  - matplotlib=3.2.1
  - cartopy=0.17.0
  - geopandas=0.7.0
  - regionmask=0.5.0
  - iris=2.4.0
  - pymc3=3.8
  - arviz=0.11.0
  - future=0.18.2
  - yaml=0.2.2
  - numba=0.48.0
  - python-dateutil=2.8.1
  - pytest=5.4.1
  - pyfakefs=4.1.0
  - esmpy=8.0.1
  - xesmf=0.3.0
  - numexpr=2.7
  - iso3166=1.0.1
