########################################################################
########################################################################
#
#  Test Harness for thinlayerreduce.pro
#
########################################################################
########################################################################
#
# Defines tests for the IDL routine thinlayerreduce to check
# the calculation of peaks and averages over thin layers.
#
# The output files are automatically compared to expected results,
# but this comparison only takes into account the data. To compare
# headers as well, run
#
# tkdiff <ThickLayerPeakFilename> <ThickLayerPeakReferenceFilename>
# tkdiff <ThickLayerAvgFilename> <ThickLayerAvgReferenceFilename>
#
# Eike Mueller, Atmospheric Dispersion Group, MetOffice, Jan 2011
#
########################################################################

import os
import re

# The following files are generated by the function WriteTestFiles():

# Original thin layer data file
ThinLayerFilename='Fields_grid1_201101191800.txt'

# Thick layer data. Thin layer data will be reduced to
# the data in these files
ThickLayerPeakFilename='Fields_grid2_201101191800.txt'
ThickLayerAvgFilename='Fields_grid3_201101191800.txt'

# Reference files. The two test function check if the data in
# ThickLayerPeakFilename is identical to the data in
# ThickLayerPeakReferenceFilename (similar test for Average data)
ThickLayerPeakReferenceFilename='thicklayers_peak.txt.reference'
ThickLayerAvgReferenceFilename='thicklayers_avg.txt.reference'

########################################################################
# Check if the data fields in two files agrees, return True if this
# is the case, False otherwise.
# 
#
# Assumes that both files are in NAME II file format. Only data after
# the second blank line is taken into account, any header information
# is ignored in the comparison.
########################################################################
def ContentsAgree(Filename1,Filename2):
    # Tolerance for comparing two float numbers
    Tolerance = 1.0E-4
    file1 = open(Filename1,'r')
    file2 = open(Filename2,'r')
    # Data only starts after the second blank line
    while not (re.match('^\\s*$',file1.readline())):
        pass
    while not (re.match('^\\s*$',file1.readline())):
        pass
    while not (re.match('^\\s*$',file2.readline())):
        pass
    while not (re.match('^\\s*$',file2.readline())):
        pass
    Line1 = file1.readline()
    Line2 = file2.readline()
    Agree = True
    while (Line1 and Line2):
        if (Line1 == None) or (Line2 == None):
            Agree = False
            print Line1,
            print Line2
            break
        else:
            SplitLine1=Line1.strip().split(',')
            if SplitLine1[-1] == '':
                SplitLine1.pop()
            SplitLine2=Line2.strip().split(',')            
            if SplitLine2[-1] == '':
                SplitLine2.pop()
            if not(len(SplitLine1) == len(SplitLine2)):
                Agree = False
                print Line1,
                print Line2
                break
            else:                
                for i in range(0,len(SplitLine1)):
                    if abs(float(SplitLine1[i]) - float(SplitLine2[i])) > Tolerance:
                        Agree = False
                        print Line1,
                        print Line2
                        break
        Line1 = file1.readline()
        Line2 = file2.readline()

    file1.close()
    file2.close()
    return Agree

########################################################################
# Run IDL to generate peaks over thin layers (in file ThinLayerFilename)
# and compare to reference file.
########################################################################
def test_ThinlayerPeaks():
    WriteTestFiles(ThinLayerFilename,
                   ThickLayerPeakReferenceFilename,
                   ThickLayerAvgReferenceFilename)
    m = re.search('Fields_([a-zA-Z]+)([0-9]+)_([0-9]+)\.txt',ThinLayerFilename)
    selgridstr=m.group(1)
    selgridno=int(m.group(2))
    seltime=str(m.group(3))
    selgridin=selgridstr+str(selgridno)
    selgridout=selgridstr+str(selgridno+1)
    idlcommand =''
    idlcommand+=''
    idlcommand+='idl << eof\n'
    idlcommand+='!path=!path+":/home/h03/apem/code/name/fcm_workspace/trunk/Code_IDLGraphics/"\n'
    idlcommand+='datadir=\'.\'\n'
    idlcommand+='seltime=\''+seltime+'\'\n'
    idlcommand+='selgridin=\''+selgridin+'\'\n'
    idlcommand+='selgridout=\''+selgridout+'\'\n'
    idlcommand+='selfield=\'Air Concentration\'\n'
    idlcommand+='selspecies=\'VOLCANIC_ASH\'\n'
    idlcommand+='thinlayerlist=['
    idlcommand+='[\'From FL000 - FL025\',\'From FL025 - FL050\'],'
    idlcommand+='[\'\',                  \'From FL075 - FL100\'],'
    idlcommand+='[\'From FL100 - FL125\',\'\'                  ]'
    idlcommand+=']\n'
    idlcommand+='thicklayerlist=[\'From FL000 - FL050\',\'From FL075 - FL100\',\'From FL100 - FL125\']\n'
    idlcommand+='reductionmethod=\'peak\'\n'
    idlcommand+='factor=2.0\n'
    idlcommand+='thinlayerreduce,'
    idlcommand+='datadir,seltime,selgridin,selgridout,'
    idlcommand+='selfield,selspecies,'
    idlcommand+='thinlayerlist,thicklayerlist,reductionmethod,'
    idlcommand+='factor=factor\n'
    idlcommand+='eof'
    (stdin,stdout,stderr)=os.popen3(idlcommand)
    print '--- stderr ---'
    for line in stderr.readlines():
        print line.rstrip()
    print '--- stdout ---'
    for line in stdout.readlines():
        print line.rstrip()
    assert ContentsAgree(ThickLayerPeakFilename,
                         ThickLayerPeakReferenceFilename)

########################################################################
# Run IDL to generate averages over thin layers (in file
# ThinLayerFilename) and compare to reference file.
########################################################################
def test_ThinlayerAvgs():
    WriteTestFiles(ThinLayerFilename,
                   ThickLayerPeakReferenceFilename,
                   ThickLayerAvgReferenceFilename)
    m = re.search('Fields_([a-zA-Z]+)([0-9]+)_([0-9]+)\.txt',ThinLayerFilename)
    selgridstr=m.group(1)
    selgridno=int(m.group(2))
    seltime=str(m.group(3))
    selgridin=selgridstr+str(selgridno)
    selgridout=selgridstr+str(selgridno+2)
    idlcommand =''
    idlcommand+=''
    idlcommand+='idl << eof\n'
    idlcommand+='!path=!path+":/home/h03/apem/code/name/fcm_workspace/trunk/Code_IDLGraphics/"\n'
    idlcommand+='datadir=\'.\'\n'
    idlcommand+='seltime=\''+seltime+'\'\n'
    idlcommand+='selgridin=\''+selgridin+'\'\n'
    idlcommand+='selgridout=\''+selgridout+'\'\n'
    idlcommand+='selfield=\'Air Concentration\'\n'
    idlcommand+='selspecies=\'VOLCANIC_ASH\'\n'
    idlcommand+='thinlayerlist=['
    idlcommand+='[\'From FL000 - FL025\',\'From FL025 - FL050\'],'
    idlcommand+='[\'\',                  \'From FL075 - FL100\'],'
    idlcommand+='[\'From FL100 - FL125\',\'\'                  ]'
    idlcommand+=']\n'
    idlcommand+='thicklayerlist=[\'From FL000 - FL050\',\'From FL075 - FL100\',\'From FL100 - FL125\']\n'
    idlcommand+='reductionmethod=\'average\'\n'
    idlcommand+='thinlayerreduce,'
    idlcommand+='datadir,seltime,selgridin,selgridout,'
    idlcommand+='selfield,selspecies,'
    idlcommand+='thinlayerlist,thicklayerlist,reductionmethod\n'
    idlcommand+='eof'
    (stdin,stdout,stderr)=os.popen3(idlcommand)
    print '--- stderr ---'
    for line in stderr.readlines():
        print line.rstrip()
    print '--- stdout ---'
    for line in stdout.readlines():
        print line.rstrip()
    assert ContentsAgree(ThickLayerAvgFilename,
                         ThickLayerAvgReferenceFilename)
    

########################################################################
# Generate thin layer input and thick layer reference files.
#
# Writes the files ThinLayerFilename, ThickLayerPeakReferenceFilename,
# ThickLayerAvgReferenceFilename to disk, so they can be read by the
# test- and comparison routines.
########################################################################
def WriteTestFiles(ThinLayerFilename,
                   ThickLayerPeakReferenceFilename,
                   ThickLayerAvgReferenceFilename):
## Thin layer input file
   file = open(ThinLayerFilename,'w')
   Contents = '''NAME III (version 6.0.1)                                        
 Title:               ASKJA_20110119_12Z
 Run time:            1155UTC 19/01/2011
 Met data:            NWP Flow.Global_PT1_flow; NWP Flow.Global_PT2_flow
 Start of release:     1150UTC 19/01/2011
 End of release:       1150UTC 20/01/2011
 Release rate:        5.4717777E-05g/s
 Release location:    16.7500W   65.0300N
 Release height:      5758.000m asl +/- 4242.000m
 Forecast duration:   131 hours
 X grid origin:         0.0000000E+00
 Y grid origin:         -90.00000    
 X grid size:                  640
 Y grid size:                  480
 X grid resolution:     0.5625000    
 Y grid resolution:     0.3750000    
 Number of fields:              5
 
                   ,                   ,                   ,                   ,                VOLCANIC,                VOLCANIC,                VOLCANIC,                VOLCANIC,                VOLCANIC,
                   ,                   ,                   ,                   ,            VOLCANIC_ASH,            VOLCANIC_ASH,            VOLCANIC_ASH,            VOLCANIC_ASH,            VOLCANIC_ASH,
                   ,                   ,                   ,                   ,    006 hr time averaged,    006 hr time averaged,    006 hr time averaged,    006 hr time averaged,    006 hr time averaged,
                   ,                   ,                   ,                   ,       Air Concentration,       Air Concentration,       Air Concentration,       Air Concentration,       Air Concentration,
                   ,                   ,                   ,                   ,                    g/m3,                    g/m3,                    g/m3,                    g/m3,                    g/m3,
                   ,                   ,                   ,                   ,      From FL000 - FL025,      From FL025 - FL050,      From FL050 - FL075,      From FL075 - FL100,      From FL100 - FL125,
             X grid,             Y grid,          Longitude,           Latitude,      1800UTC 19/01/2011,      1800UTC 19/01/2011,      1800UTC 19/01/2011,      1800UTC 19/01/2011,      1800UTC 19/01/2011,
 
        1.500000,         333.500000,           0.281250,          34.687500,          0.0,                     0.0,                     4.0,                     4.0,                     5.0,
        1.500000,         334.500000,           0.281250,          35.062500,          1.0,                     4.0,                     7.0,                     3.0,                     0.0,
        1.500000,         335.500000,           0.281250,          35.437500,          1.0,                     0.0,                     9.0,                     3.0,                     8.0,'''
   file.write(Contents)
   file.close()
   
## Thick layer (peaks) file
   file = open(ThickLayerPeakReferenceFilename,'w')
   Contents='''NAME III (version 6.0.1)
Title                         :  ASKJA_20110119_12Z                                          
Run time                      :  1155UTC 19/01/2011                                          
Met data                      :  NWP Flow.Global_PT1_flow; NWP Flow.Global_PT2_flow          
Start of release              :  1150UTC 19/01/2011                                          
End of release                :  1150UTC 20/01/2011                                          
Release rate                  :  5.4717777E-05g/s                                            
Release location              :  16.7500W   65.0300N                                         
Release height                :  5758.000m asl +/- 4242.000m                                 
Forecast duration             :  131 hours                                                   
X grid origin                 :  0.0000000E+00                                               
Y grid origin                 :  -90.00000                                                   
X grid size                   :  640                                                         
Y grid size                   :  480                                                         
X grid resolution             :  0.5625000                                                   
Y grid resolution             :  0.3750000                                                   
 Number of fields             :              3                                               

                   ,                   ,                   ,                   ,                VOLCANIC,                VOLCANIC,                VOLCANIC,
                   ,                   ,                   ,                   ,            VOLCANIC_ASH,            VOLCANIC_ASH,            VOLCANIC_ASH,
                   ,                   ,                   ,                   ,    006 hr time averaged,    006 hr time averaged,    006 hr time averaged,
                   ,                   ,                   ,                   ,       Air Concentration,       Air Concentration,       Air Concentration,
                   ,                   ,                   ,                   ,                    g/m3,                    g/m3,                    g/m3,
                   ,                   ,                   ,                   ,      From FL000 - FL050,      From FL075 - FL100,      From FL100 - FL125,
             X grid,             Y grid,          Longitude,           Latitude,      1800UTC 19/01/2011,      1800UTC 19/01/2011,      1800UTC 19/01/2011,
             
        1.500000,         333.500000,           0.281250,          34.687500,          0.0,                     8.0,                    10.0,
        1.500000,         334.500000,           0.281250,          35.062500,          8.0,                     6.0,                     0.0,
        1.500000,         335.500000,           0.281250,          35.437500,          2.0,                     6.0,                    16.0,'''
   file.write(Contents)
   file.close()

# Thick layer average reference file
   file = open(ThickLayerAvgReferenceFilename,'w')
   Contents='''NAME III (version 6.0.1)
Title                         :  ASKJA_20110119_12Z                                          
Run time                      :  1155UTC 19/01/2011                                          
Met data                      :  NWP Flow.Global_PT1_flow; NWP Flow.Global_PT2_flow          
Start of release              :  1150UTC 19/01/2011                                          
End of release                :  1150UTC 20/01/2011                                          
Release rate                  :  5.4717777E-05g/s                                            
Release location              :  16.7500W   65.0300N                                         
Release height                :  5758.000m asl +/- 4242.000m                                 
Forecast duration             :  131 hours                                                   
X grid origin                 :  0.0000000E+00                                               
Y grid origin                 :  -90.00000                                                   
X grid size                   :  640                                                         
Y grid size                   :  480                                                         
X grid resolution             :  0.5625000                                                   
Y grid resolution             :  0.3750000                                                   
 Number of fields             :              3                                               

                   ,                   ,                   ,                   ,                VOLCANIC,                VOLCANIC,                VOLCANIC,
                   ,                   ,                   ,                   ,            VOLCANIC_ASH,            VOLCANIC_ASH,            VOLCANIC_ASH,
                   ,                   ,                   ,                   ,    006 hr time averaged,    006 hr time averaged,    006 hr time averaged,    006 hr time averaged,    006 hr time averaged,                   
                   ,                   ,                   ,                   ,       Air Concentration,       Air Concentration,       Air Concentration,
                   ,                   ,                   ,                   ,                    g/m3,                    g/m3,                    g/m3,
                   ,                   ,                   ,                   ,      From FL000 - FL050,      From FL075 - FL100,      From FL100 - FL125,
             X grid,             Y grid,          Longitude,           Latitude,      1800UTC 19/01/2011,      1800UTC 19/01/2011,      1800UTC 19/01/2011,
             
        1.500000,         333.500000,           0.281250,          34.687500,          0.0,                     4.0,                     5.0,
        1.500000,         334.500000,           0.281250,          35.062500,          2.5,                     3.0,                     0.0,
        1.500000,         335.500000,           0.281250,          35.437500,          0.5,                     3.0,                     8.0,'''
   file.write(Contents)
   file.close()

if (__name__ == '__main__'):
    test_ThinlayerPeaks()
    test_ThinlayerAvgs()
