#!/bin/ksh
#
# Standard script to compile and install GRIB API software
# as shared object libraries. 
#
###########################################################################

echo "** Compiling and installing GRIB_API for use with NAME **"

# Set directories for the GRIB_API source, local definitions and install locations

GRIB_API_BASEDIR=`pwd`
NAMEIII_BASEDIR=`dirname ${GRIB_API_BASEDIR}`

GRIB_API_DIR="${GRIB_API_BASEDIR}/grib_api-1.9.5"
LOCAL_DEFN_DIR="${GRIB_API_BASEDIR}/local"
INSTALL_DIR="${NAMEIII_BASEDIR}/SharedLibraries_Linux"

echo "\nGRIB_API source is ${GRIB_API_DIR}"
echo "Installing GRIB_API in ${INSTALL_DIR}"

# Protect any existing 32-bit 'include' directory during a 64-bit compilation
# (this ensures that both 32-bit and 64-bit versions can be held in the library)

if test `uname` = 'Linux'
then
  if test `uname -p` = 'x86_64'
  then
    if [[ -d ${INSTALL_DIR}/include ]]
    then
      mv ${INSTALL_DIR}/include ${INSTALL_DIR}/include_protected
    fi
  fi
fi

cd ${GRIB_API_DIR}

# Run configure script
#  - specify Intel Fortran compiler on Linux explicitly
#  - compile with -fPIC in FCFLAGS, FFLAGS, CFLAGS
#  - install location specified in --prefix
#  - Jasper (file compression utility) not installed so specify --disable-jpeg

echo "\nRunning configure script"

FC=ifort F77=ifort FCFLAGS=-fPIC FFLAGS=-fPIC CFLAGS=-fPIC ./configure --prefix=${INSTALL_DIR} --disable-jpeg

# Clean up after previous compilation $$ need to do this?

make clean

# Compile and install code using make and make install

echo "\nMaking GRIB_API library ..."
make

echo "\nChecking GRIB_API compilation ..."
make check

echo "\nInstalling GRIB_API library ..."
make install

# The creation of shared object libraries builds on work by Tom Green, see
# http://fcm2/projects/UM/wiki/InteropProject/HowtoSharedLibrary

# Created shared object libraries libgrib_api.so, libgrib_api_f90.so, libgrib_api_f77.so

echo "\nBuilding .so library files ..."

TEMP_DIR="${INSTALL_DIR}/lib/temp"
mkdir ${TEMP_DIR}
cd ${TEMP_DIR}

for lib in libgrib_api libgrib_api_f90 libgrib_api_f77 ; do

  mv ../${lib}.a .
  ar -x ${lib}.a
  ld -shared -o ${lib}.so *.o
  rm *.o *.a
  
  if test `uname` = 'Linux'
  then
    if test `uname -p` = 'x86_64'
    then
      mv ${lib}.so ../${lib}_64bit.so
    else
      mv ${lib}.so ../${lib}.so
    fi
  fi

done

rmdir ${TEMP_DIR}

# Rename the 'include' directory for a 64-bit compilation and restore any protected 32-bit 'include' directory
# (this ensures that both 32-bit and 64-bit versions can be held in the library)
  
if test `uname` = 'Linux'
then
  if test `uname -p` = 'x86_64'
  then
    mv ${INSTALL_DIR}/include ${INSTALL_DIR}/include_64bit
    if [[ -d ${INSTALL_DIR}/include_protected ]]
    then
      mv ${INSTALL_DIR}/include_protected ${INSTALL_DIR}/include
    fi
  fi
fi

# Install local definitions

echo "\nInstalling local definitions ..."
cp -r ${LOCAL_DEFN_DIR} ${INSTALL_DIR}/.

echo "** GRIB_API compiled and installed for use with NAME **"

exit 0
